---
- hosts: master
  become: yes
  tasks:
    - name: install public keys
      ansible.posix.authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '<path-to-key.pub>') }}"
    - name: Ignore sudoer's validation
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
